# version: '2.6.2'

services:
  blog-server:
    build:
      context: .
    image: blog-server
    volumes:
      - "./:/home/app/www/blog-server/"
    environment:
      - RAILS_ENV=development
    ports:
      - 3000:3000
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bin/rake db:migrate && rails server -b 0.0.0.0"